version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  frontend:
    container_name: stackmarket-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    stdin_open: true
  graphql-engine:
    image: hasura/graphql-engine:v1.3.1
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - ./.env
volumes:
  db_data:

