version: "3"

services:
  postgres:
    container_name: stackmarket-postgres
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  upload:
    container_name: stackmarket-s3-api
    restart: always
    image: ecumene/stackupload:latest
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - ./stackupload/.env

  s3-minio:
    container_name: stackmarket-minio
    restart: always
    image: minio/minio:latest
    command: minio server /data
    ports:
      - "127.0.0.1:9000:9000"
    env_file:
      - ./stackupload/.env

  auth:
    container_name: stackmarket-auth
    restart: always
    image: ecumene/stacklogin:latest
    ports:
      - "127.0.0.1:8082:8082"
    env_file:
      - ./stacklogin/.env

  frontend:
    container_name: stackmarket-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./frontend/.env
    stdin_open: true

  graphql-engine:
    container_name: stackmarket-graphql-engine
    restart: always
    image: hasura/graphql-engine:v1.3.1
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - "postgres"
    env_file:
      - ./.env

volumes:
  db_data:
